[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
gas_report = true
coverage = true
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
	"@uniswap/v3-core/contracts/=lib/v3-core/contracts/"
]